const {json,getSupabase,getUser,requireActive,emergency,specialty,geminiJSON,usage}=require('./_lib');
module.exports=async(req,res)=>{try{const sb=getSupabase();const {user,profile}=await getUser(req);requireActive(profile);const {message,patient_context='unknown'}=req.body||{};if(!message)return json(res,400,{error:'Message required'});
 const em=emergency(message);const spec=specialty(message);if(em)await sb.from('risk_events').insert({user_id:user.id,risk:'emergency',message});
 const {data:recent}=await sb.from('chat_messages').select('role,content,patient_context,created_at').eq('user_id',user.id).order('created_at',{ascending:false}).limit(8);
 const system=`You are Neura, a Bangladesh-first AI health companion. You are not a doctor. You must never prescribe medicine, change dose, stop medicine, or diagnose with certainty. Your job is to ask safe follow-up questions, identify emergency red flags, organize symptoms, suggest the correct specialist type, and recommend consulting qualified doctors/clinics. Always ask whether the user is the registered patient or asking for someone else if unclear. Only update patient memory when patient_context is self. If someone_else, give guidance but do not store as patient disease. Use simple warm English/Bangla depending on user. If emergency red flags: tell user to call Bangladesh emergency 999 or nearest ER immediately. Output strict JSON: {reply,risk,specialist,followUps,shouldUpdateMemory,memoryNote,searchQuery}. Profile: ${JSON.stringify(profile).slice(0,1800)} Recent: ${JSON.stringify(recent||[]).slice(0,2000)} Current patient_context:${patient_context}. Detected emergency:${em}. Detected specialist:${spec}.`;
 let out;try{out=await geminiJSON(system+'\nUser: '+message)}catch(e){out={reply: em?'⚠️ This may be an emergency. Call 999 or go to the nearest emergency department now.':'I need a few details: are you the registered patient or asking for someone else? Age, how long this has happened, severity, and any red flags like chest pain, breathing trouble, fainting, severe pain, or high fever?',risk:em?'emergency':'needs_more_info',specialist:spec,followUps:[]}}
 if(em)out.risk='emergency'; if(!out.specialist)out.specialist=spec;
 await sb.from('chat_messages').insert([{user_id:user.id,role:'user',content:message,patient_context,risk:out.risk},{user_id:user.id,role:'agent',content:out.reply||'',patient_context,risk:out.risk}]);
 if(patient_context==='self'&&out.shouldUpdateMemory&&out.memoryNote){const newMem=[profile.memory_summary||'',out.memoryNote].filter(Boolean).join('\n').slice(-5000);await sb.from('profiles').update({memory_summary:newMem,updated_at:new Date().toISOString()}).eq('id',user.id)}
 await usage(sb,user.id,'ai_chat',{risk:out.risk,specialist:out.specialist});
 return json(res,200,{ok:true,...out});
}catch(e){json(res,e.message.includes('SUBSCRIPTION')?402:500,{error:e.message})}}
